apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  namespace: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app # Match with MARK C
  template:
    metadata:
      labels:
        app: react-app # Match with MARK C
    spec:
      containers:
        - name: react-app-container
          image: johnmfiskander.azurecr.io/dockerized-react-app
          ports:
            - containerPort: 4173

---

# wordpress/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: react-app # Match with namespace
spec:
  type: LoadBalancer
  ports:
  - port: 4173 # Port that publicly exposed to internet
    targetPort: 4173 # Match with MARK C.1
    protocol: TCP
  selector:
    app: react-app # Match with MARK C