on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
jobs:
  test:
    name: preparation of env. and running initial test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-node@v2.5.2
    - run: npm i -g pnpm
    - run: pnpm i
    - run: pnpm run test
    
    
    
  
    
  
