on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
jobs:
  preparation:
    name: preparation of env. and running initial test
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup NodeJs
      uses: actions/setup-node@v2.5.2
      with: 
        node-version: 16
    - name: Checkout the code
      uses: actions/checkout@v3.5.2
    - name: Just list the current directory for fun ;) <helps in debugging!>
      run: ls
    - name: install pnpm
      run: npm i -g pnpm
    - name: install react project dependencies
      run: pnpm i
    - name: run test
      run: pnpm run test


    
    
    
  
    
  
